### ISSUE TITLE
Couldn't Achive the app purpose

### ISSUE THREAD

**Issue by khaledboka** [cartologic/cartoview_geo_collect#40]
after I Tried the following, Couldn't find the created point/points on the map or even the layer
**Stage 1:**
(user: ev, pass:123456)
Selected map: Map x
Selected Layer: animal_abuse_lacity
Form Customization: Default state
selected loge,
App Title: Testing Collection new points 
abstract:At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium
accesss: em, vo
keywords: keyword1
navigation tools: default state,

App instance create successfullt,

**Stage 2:**
chosen the following:
<img width="793" alt="screen shot 2017-12-04 at 1 48 37 pm" src="https://user-images.githubusercontent.com/13452248/33551445-0b72492c-d8fa-11e7-9b25-c9c92243cd00.png">

Clicked next and Successfully: **Your Data Saved Successfully**

please Notice that I tried to do extra check up and launched cartoview feature list and found the points in the list of feature but not rendered on the map

**Comment by hishamkaram** [comment]
fixed in the latest version
