### ISSUE TITLE
Extra Options 

### ISSUE THREAD

**Issue by khaledboka** [cartologic/cartoview_geo_collect#41]
The second "**options**" expected to be "Extra Options", Otherwise explain what are the differences and usage of both

<img width="442" alt="screen shot 2017-12-04 at 2 42 21 pm" src="https://user-images.githubusercontent.com/13452248/33553517-c132b9fc-d901-11e7-9e7a-a53ae4b72b34.png">

**Comment by hishamkaram** [comment]
PR: https://github.com/cartologic/cartoview_geo_collect/pull/44
